version: "3"
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "directus"
      MYSQL_USER: "directus"
      MYSQL_PASSWORD: "directus"
      MYSQL_ROOT_PASSWORD: "directus"
    ports:
      - "3306:3306"
    networks:
      - cms-network
    volumes:
      - ./data/db:/var/lib/mysql

  directus:
    # image: directus/directus:v8-apache
    build: ./config
    ports:
      - "8765:80"
    environment:
      DIRECTUS_APP_ENV: "production"
      DIRECTUS_INSTALL_TITLE: "OAAM"
      DIRECTUS_AUTH_PUBLICKEY: "some random secret"
      DIRECTUS_AUTH_SECRETKEY: "another random secret"
      DIRECTUS_DATABASE_HOST: "mysql"
      DIRECTUS_DATABASE_PORT: "3306"
      DIRECTUS_DATABASE_NAME: "directus"
      DIRECTUS_DATABASE_USERNAME: "directus"
      DIRECTUS_DATABASE_PASSWORD: "directus"
    volumes:
      - ./data/uploads:/var/directus/public/uploads
    depends_on:
      - mysql
    networks:
      - cms-network

networks:
  cms-network:
    driver: bridge
